In [3]:
#1: Create two NumPy arrays representing the daily step counts of two friends over a week and use element-wise addition, subtraction, multiplication, and division to compare their activity levels.

import numpy as np

friend1 = np.array([8000, 7500, 9000, 8500, 10000, 9500, 8700])
friend2 = np.array([7000, 8000, 8500, 9000, 9500, 10000, 9200])

print("Addition:")
print(friend1 + friend2)

print("\nSubtraction:")
print(friend1 - friend2)

print("\nMultiplication:")
print(friend1 * friend2)

print("\nDivision:")
print(friend1 / friend2)

Addition:
[15000 15500 17500 17500 19500 19500 17900]

Subtraction:
[1000 -500  500 -500  500 -500 -500]

Multiplication:
[56000000 60000000 76500000 76500000 95000000 95000000 80040000]

Division:
[1.14285714 0.9375     1.05882353 0.94444444 1.05263158 0.95
 0.94565217]


In [2]:
#2: Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices representing user-song interaction scores (user preferences and song popularity), use dot() and matmul() to compute the final recommendation matrix and explain the difference between the two results.
import numpy as np

user_preferences = np.array([
    [5, 3, 4],
    [4, 5, 2],
    [3, 4, 5]
])

song_popularity = np.array([
    [2, 1, 3],
    [4, 2, 1],
    [3, 5, 2]
])

recommendation_dot = np.dot(user_preferences, song_popularity)
recommendation_matmul = np.matmul(user_preferences, song_popularity)

print("Using dot():")
print(recommendation_dot)

print("\nUsing matmul():")
print(recommendation_matmul)

Using dot():
[[34 31 26]
 [34 24 21]
 [37 36 23]]

Using matmul():
[[34 31 26]
 [34 24 21]
 [37 36 23]]


In [3]:
#3: Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram image, use transpose (T) to rotate the image and then calculate the mean, median, standard deviation, and variance of the pixel values.
import numpy as np

pixels = np.array([
    [100, 120, 130, 140],
    [110, 125, 135, 145],
    [115, 128, 138, 150],
    [118, 130, 140, 155]
])

transposed = pixels.T

print("Transposed Matrix:")
print(transposed)

print("\nMean:", np.mean(pixels))
print("Median:", np.median(pixels))
print("Standard Deviation:", np.std(pixels))
print("Variance:", np.var(pixels))

Transposed Matrix:
[[100 110 115 118]
 [120 125 128 130]
 [130 135 138 140]
 [140 145 150 155]]

Mean: 129.9375
Median: 130.0
Standard Deviation: 14.441557871296295
Variance: 208.55859375


In [4]:
#4: Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid and use np.linalg.inv(), np.linalg.det(), and np.linalg.eig() to compute its inverse, determinant, and eigenvalues/eigenvectors.
import numpy as np

ratings = np.array([
    [4, 2, 1],
    [3, 5, 2],
    [1, 2, 4]
])

inverse = np.linalg.inv(ratings)
determinant = np.linalg.det(ratings)
eigenvalues, eigenvectors = np.linalg.eig(ratings)

print("Inverse Matrix:")
print(inverse)

print("\nDeterminant:")
print(determinant)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Inverse Matrix:
[[ 0.35555556 -0.13333333 -0.02222222]
 [-0.22222222  0.33333333 -0.11111111]
 [ 0.02222222 -0.13333333  0.31111111]]

Determinant:
45.000000000000014

Eigenvalues:
[8.16227766 1.83772234 3.        ]

Eigenvectors:
[[-0.47140452 -0.47140452 -0.43643578]
 [-0.74535599  0.74535599 -0.21821789]
 [-0.47140452 -0.47140452  0.87287156]]


In [5]:
#5: Create a NumPy array of shape (2, 6) representing the number of orders placed on Swiggy in two cities over 6 days. Reshape it to (3, 4), flatten it, split it into two equal parts, and then stack both parts vertically.
import numpy as np

orders = np.array([
    [10, 12, 15, 18, 20, 22],
    [8, 10, 12, 14, 16, 18]
])

print("Original Shape:")
print(orders)

reshaped = orders.reshape(3, 4)
print("\nReshaped (3x4):")
print(reshaped)

flattened = reshaped.flatten()
print("\nFlattened:")
print(flattened)

part1, part2 = np.split(flattened, 2)

print("\nPart 1:")
print(part1)

print("\nPart 2:")
print(part2)

stacked = np.vstack((part1, part2))

print("\nVertically Stacked:")
print(stacked)

Original Shape:
[[10 12 15 18 20 22]
 [ 8 10 12 14 16 18]]

Reshaped (3x4):
[[10 12 15 18]
 [20 22  8 10]
 [12 14 16 18]]

Flattened:
[10 12 15 18 20 22  8 10 12 14 16 18]

Part 1:
[10 12 15 18 20 22]

Part 2:
[ 8 10 12 14 16 18]

Vertically Stacked:
[[10 12 15 18 20 22]
 [ 8 10 12 14 16 18]]
