In [1]:
#1: Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items on Zomato. Use slicing to extract the ratings given by the second and third users only.

import numpy as np

ratings = np.array([
    [4, 5, 3, 4, 5],  # User 1
    [5, 4, 4, 3, 5],  # User 2
    [3, 5, 4, 5, 4],  # User 3
    [4, 3, 5, 4, 5]   # User 4
])

selected_ratings = ratings[1:3]

print("All Ratings:\n", ratings)
print("\nRatings of 2nd and 3rd Users:\n", selected_ratings)

All Ratings:
 [[4 5 3 4 5]
 [5 4 4 3 5]
 [3 5 4 5 4]
 [4 3 5 4 5]]

Ratings of 2nd and 3rd Users:
 [[5 4 4 3 5]
 [3 5 4 5 4]]


In [2]:
#2: Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select only the days where the steps were greater than 8000.

import numpy as np

steps = np.array([7500, 8200, 9000, 7000, 10000,
                  8500, 7800, 9500, 8100, 6000])

high_steps = steps[steps > 8000]

print("Days with steps greater than 8000:")
print(high_steps)

Days with steps greater than 8000:
[ 8200  9000 10000  8500  9500  8100]


In [3]:
#3: Create a NumPy array of IPL team scores for 8 matches. Use fancy indexing to select the scores from matches 2, 5, and 7, and print them.

import numpy as np

scores = np.array([180, 165, 200, 175, 210, 190, 220, 185])

selected_scores = scores[[1, 4, 6]]

print("Scores from matches 2, 5, and 7:")
print(selected_scores)

Scores from matches 2, 5, and 7:
[165 210 220]


In [4]:
#4: Suppose you have a NumPy array of product prices from Flipkart. Use broadcasting to apply a 10% discount to all prices and print the new array.

import numpy as np

prices = np.array([500, 1200, 750, 2000, 1500])

discounted_prices = prices * 0.90

print("Original Prices:", prices)
print("Discounted Prices:", discounted_prices)

Original Prices: [ 500 1200  750 2000 1500]
Discounted Prices: [ 450. 1080.  675. 1800. 1350.]


In [5]:
#5: Given a NumPy array of user ratings (can be negative, zero, or positive) for songs on Spotify, use boolean masking to set all negative ratings to zero, keeping other ratings unchanged.

import numpy as np

ratings = np.array([5, -2, 3, -1, 4, 0, -3, 2])

ratings[ratings < 0] = 0

print("Updated Ratings:")
print(ratings)

Updated Ratings:
[5 0 3 0 4 0 0 2]
