In [1]:
#1: Install NumPy in your Python environment using pip, then create a Python file called insta_likes.py and import numpy as np at the top.
# insta_likes.py

import numpy as np

print("NumPy imported successfully!")

NumPy imported successfully!


In [2]:
#2: Create a NumPy array called followers using np.array() that stores the follower counts for 5 Instagram influencers: [1200, 15000, 67000, 340000, 1250000]. Print the array, its shape, number of dimensions, and data type.

import numpy as np

followers = np.array([1200, 15000, 67000, 340000, 1250000])

print("Array:", followers)
print("Shape:", followers.shape)
print("Dimensions:", followers.ndim)
print("Data Type:", followers.dtype)

Array: [   1200   15000   67000  340000 1250000]
Shape: (5,)
Dimensions: 1
Data Type: int64


In [3]:
#3: Use np.arange() to generate an array of order IDs for 10 consecutive Zomato orders starting from 101. Print the array and its size.

import numpy as np

order_ids = np.arange(101, 111)

print("Order IDs:", order_ids)
print("Size:", order_ids.size)

Order IDs: [101 102 103 104 105 106 107 108 109 110]
Size: 10


In [4]:
#4: Create a 3x3 NumPy array using np.eye() to represent a 'like' identity matrix for a new Spotify playlist feature. Print the matrix and explain what the diagonal values represent in a comment.


import numpy as np

identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
#5: Convert a Python list of cricket scores [45, 67, 120, 89, 54] to a NumPy array, then use the .itemsize attribute to print how many bytes each score takes in memory.

import numpy as np

scores = [45, 67, 120, 89, 54]

scores_array = np.array(scores)

print("NumPy Array:", scores_array)
print("Bytes per element:", scores_array.itemsize)

NumPy Array: [ 45  67 120  89  54]
Bytes per element: 8
